---
- hosts: web
  become: yes
  tasks:
    - name: be sure GPG key of Docker installed
      apt_key: url=https://download.docker.com/linux/debian/gpg
    - name: be sure Docker repository installed
      apt_repository: repo="deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"
    - name: be updated apt cache
      apt: update_cache=yes
    - name: be sure os standard packages installed
      apt: name={{ item }} state=present
      with_items:
        - apt-transport-https
        - docker-ce
    - name: be sure docker daemon settings copied
      copy: src=daemon.json dest=/etc/docker/daemon.json owner=root group=root mode=0644
    - name: be sure docker-compose installed
      get_url: url='https://github.com/docker/compose/releases/download/1.19.0/docker-compose-Linux-x86_64' dest=/usr/local/bin/docker-compose owner=root group=root mode=0755
    - name: be sure massr installed
      git: repo=https://github.com/wasamas/wasamas.git dest=/opt/massr clone=yes
    - name: be sure .env of massr copied
      copy: src=.env dest=/opt/massr/.env owner=root group=root mode=0600
    - name: be sure wasamas.service copied
      copy: src=wasamas.service dest=/etc/systemd/system/wasamas.service owner=root group=root mode=0644
    - name: restart wasamas.service
      systemd:
        name: wasamas.service
        state: restarted
        daemon_reload: yes
        enabled: yes
